<!--
  文件职责 / File responsibility
  使用扩展经典方案的三段 Tube 曲线精确渲染云狐尾巴与尾尖能量。
  Renders the Cloud Fox tail and tail-tip energy with the extension classic scheme's exact three Tube curves.
-->
<script setup lang="ts">
import { useLoop } from '@tresjs/core'
import { AdditiveBlending, CatmullRomCurve3, Color, Euler, Vector3 } from 'three'
import type { Group, MeshStandardMaterial } from 'three'
import { EXTENSION_CLASSIC_CLOUD_FOX_SCHEME, type VisualCurve, type VisualEuler3 } from '~/domain/chrome-extension-cloud-fox-profile'
import type { CloudFoxStudioBehavior } from '~/domain/pet-studio-phase4'
import type { MultiSpeciesAppearanceRecipe } from '~/domain/pet-species-registry'
const props=defineProps<{appearance:MultiSpeciesAppearanceRecipe;behavior:CloudFoxStudioBehavior}>(),s=EXTENSION_CLASSIC_CLOUD_FOX_SCHEME
const v=(a:readonly number[])=>new Vector3(a[0]||0,a[1]||0,a[2]||0),sc=(a:readonly number[],n:number)=>new Vector3((a[0]||0)*n,(a[1]||0)*n,(a[2]||0)*n),r=(a:readonly number[])=>new Euler(a[0]||0,a[1]||0,a[2]||0),curve=(p:VisualCurve,n:number)=>new CatmullRomCurve3(p.map(x=>sc(x,n)))
const tail=shallowRef<Group>(),materials=shallowRef<MeshStandardMaterial[]>([]),n=computed(()=>props.appearance.proportions.tailLength),w=computed(()=>props.appearance.proportions.tailWidth),baseCurve=computed(()=>curve(s.model.tail.baseCurve,n.value)),midCurve=computed(()=>curve(s.model.tail.midCurve,n.value)),tipCurve=computed(()=>curve(s.model.tail.tipCurve,n.value))
const rotation=computed(()=>{const b=s.model.tail.rotation,m:Record<string,VisualEuler3>={left:b,right:[b[0],Math.PI+b[1],-b[2]],up:[b[0],b[1],1.05],down:[b[0],b[1],-1.08],back:[b[0],-1.08,b[2]],forward:[b[0],1.08,b[2]]};return r(m[props.appearance.tailDesign.direction]||b)})
const glow=computed(()=>props.appearance.glow.mode==='emotion'?({idle:props.appearance.palette.primaryGlow,greeting:props.appearance.palette.secondaryGlow,jumping:'#ffd36a',stretching:props.appearance.palette.antennaGlow,spinning:'#ff78c8',resting:'#8190c9'}[props.behavior]):props.appearance.palette.tailGlow)
function refGlow(x:unknown){const m=x as MeshStandardMaterial|null;if(m&&!materials.value.includes(m))materials.value.push(m)}const rainbow=new Color()
useLoop().onBeforeRender(({elapsed})=>{if(tail.value){const sp=props.behavior==='spinning',g=props.behavior==='greeting'||props.behavior==='jumping',re=props.behavior==='resting',a=sp?.24:g?.18:re?.025:.075,z=sp?8.4:g?6.8:re?1.2:2.5;tail.value.rotation.set(rotation.value.x+Math.cos(elapsed*z*.5)*a*.18,rotation.value.y,rotation.value.z+Math.sin(elapsed*z)*a)}const p=1+Math.sin(elapsed*props.appearance.glow.pulseSpeed*3.5)*.12;if(props.appearance.glow.mode==='rainbow')rainbow.setHSL((elapsed*.11)%1,.86,.64);for(const m of materials.value){m.emissiveIntensity=props.appearance.glow.intensity*p;if(props.appearance.glow.mode==='rainbow'){m.color.copy(rainbow);m.emissive.copy(rainbow)}}})
</script>
<template><TresGroup ref="tail" :position="v(s.model.tail.position)" :rotation="rotation"><TresMesh cast-shadow><TresTubeGeometry :args="[baseCurve,24,s.model.tail.baseRadius*w,14,false]"/><TresMeshStandardMaterial :color="appearance.palette.coatShadow" :roughness=".32" :metalness=".02"/></TresMesh><TresGroup :position="sc(s.model.tail.midPosition,n)" :rotation="r(s.model.tail.midRotation)"><TresMesh><TresTubeGeometry :args="[midCurve,22,s.model.tail.midRadius*w,14,false]"/><TresMeshStandardMaterial :color="appearance.palette.coat" :roughness=".27" :metalness=".02"/></TresMesh><TresGroup :position="sc(s.model.tail.tipPosition,n)" :rotation="r(s.model.tail.tipRotation)"><TresMesh><TresTubeGeometry :args="[tipCurve,20,s.model.tail.tipRadius*w,14,false]"/><TresMeshStandardMaterial :ref="refGlow" :color="glow" :emissive="appearance.glow.tailEnabled?glow:'#000000'" :emissive-intensity="appearance.glow.tailEnabled?appearance.glow.intensity:0" :roughness=".14" :metalness=".04"/></TresMesh><TresMesh :position="sc(s.model.tail.energyPosition,n)"><TresSphereGeometry :args="[s.model.tail.energyRadius*w,28,28]"/><TresMeshBasicMaterial :color="glow" :tone-mapped="false"/></TresMesh><TresMesh :position="sc(s.model.tail.auraPosition,n)" :scale="v([s.model.tail.auraScale,s.model.tail.auraScale,s.model.tail.auraScale])"><TresSphereGeometry :args="[s.model.tail.auraRadius*w,24,24]"/><TresMeshBasicMaterial :color="glow" transparent :opacity=".34" :blending="AdditiveBlending" :depth-write="false"/></TresMesh></TresGroup></TresGroup></TresGroup></template>
