<!--
  文件职责 / File responsibility
  使用扩展经典方案渲染云狐身体、四肢、阴影、能量核心和身份标志。
  Renders the Cloud Fox body, limbs, shadows, energy core, and identity marks from the extension classic scheme.
-->
<script setup lang="ts">
import { useLoop } from '@tresjs/core'
import { CanvasTexture, DoubleSide, Euler, Vector3 } from 'three'
import { EXTENSION_CLASSIC_CLOUD_FOX_SCHEME } from '~/domain/chrome-extension-cloud-fox-profile'
import type { CloudFoxStudioBehavior, SymbolChannelRecipe } from '~/domain/pet-studio-phase4'
import type { MultiSpeciesAppearanceRecipe } from '~/domain/pet-species-registry'
const props=defineProps<{appearance:MultiSpeciesAppearanceRecipe;behavior:CloudFoxStudioBehavior}>(),s=EXTENSION_CLASSIC_CLOUD_FOX_SCHEME
const v=(a:readonly number[])=>new Vector3(a[0]||0,a[1]||0,a[2]||0),sc=(a:readonly number[],x=1,y=x,z=x)=>new Vector3((a[0]||0)*x,(a[1]||0)*y,(a[2]||0)*z),r=(a:readonly number[])=>new Euler(a[0]||0,a[1]||0,a[2]||0)
const bodyScale=computed(()=>sc(s.model.body.scale,props.appearance.proportions.bodyWidth,props.appearance.proportions.bodyHeight,props.appearance.proportions.bodyDepth)),pawX=computed(()=>s.model.frontPaw.offset[0]*props.appearance.proportions.limbSpacing),left=shallowRef<any>(),right=shallowRef<any>(),chestTexture=shallowRef<CanvasTexture>(),backTexture=shallowRef<CanvasTexture>()
function texture(x:SymbolChannelRecipe){if(!import.meta.client)return;const c=document.createElement('canvas');c.width=c.height=256;const g=c.getContext('2d');if(!g)return;g.textAlign='center';g.textBaseline='middle';g.font='900 142px system-ui';g.shadowColor=x.color;g.shadowBlur=18+x.glowIntensity*18;g.fillStyle=x.color;g.fillText(x.text.slice(0,3).toUpperCase(),128,132);g.shadowBlur=6;g.fillStyle='#fff';g.globalAlpha=.55;g.fillText(x.text.slice(0,3).toUpperCase(),128,128);const t=new CanvasTexture(c);t.needsUpdate=true;return t}
watch(()=>props.appearance.symbols.chest,x=>{chestTexture.value?.dispose();chestTexture.value=texture(x)},{immediate:true,deep:true});watch(()=>props.appearance.symbols.back,x=>{backTexture.value?.dispose();backTexture.value=texture(x)},{immediate:true,deep:true});onBeforeUnmount(()=>{chestTexture.value?.dispose();backTexture.value?.dispose()})
useLoop().onBeforeRender(({elapsed,delta})=>{if(!left.value||!right.value)return;const st=props.behavior==='stretching',g=props.behavior==='greeting',raised=st?.5:0,wave=g?Math.max(0,Math.sin(elapsed*9))*.14:0;left.value.position.y+=(s.model.frontPaw.offset[1]+raised-left.value.position.y)*Math.min(1,delta*8);right.value.position.y+=(s.model.frontPaw.offset[1]+raised+wave-right.value.position.y)*Math.min(1,delta*8)})
</script>
<template><TresMesh :position="v(s.model.shadow.softPosition)" :rotation="r([-Math.PI/2,0,0])"><TresCircleGeometry :args="[s.model.shadow.softRadius,48]"/><TresMeshBasicMaterial :color="s.model.shadow.softColor" transparent :opacity="s.model.shadow.softOpacity"/></TresMesh><TresMesh :position="v(s.model.shadow.corePosition)" :rotation="r([-Math.PI/2,0,0])"><TresCircleGeometry :args="[s.model.shadow.coreRadius,48]"/><TresMeshBasicMaterial :color="s.model.shadow.coreColor" transparent :opacity="s.model.shadow.coreOpacity"/></TresMesh>
<TresMesh :position="v(s.model.body.position)" :scale="bodyScale" cast-shadow><TresBoxGeometry v-if="appearance.parts.bodyShape==='rounded-cube'" :args="[1.72,1.72,1.72,8,8,8]"/><TresSphereGeometry v-else :args="[s.model.body.radius,64,64]"/><TresMeshStandardMaterial :color="appearance.palette.coatShadow" :roughness=".34" :metalness=".04"/></TresMesh><TresMesh :position="v(s.model.body.warmPatchPosition)" :scale="sc(s.model.body.warmPatchScale,appearance.proportions.bodyWidth,appearance.proportions.bodyHeight,1)"><TresSphereGeometry :args="[1,48,48]"/><TresMeshStandardMaterial :color="appearance.palette.coatWarm" :roughness=".4"/></TresMesh>
<TresGroup v-for="side in [-1,1]" :key="`fp${side}`" :ref="side<0?(n:any)=>left=n:(n:any)=>right=n" :position="v([side*pawX,s.model.frontPaw.offset[1],s.model.frontPaw.offset[2]])" :scale="v([appearance.proportions.limbThickness,appearance.proportions.limbLength,appearance.proportions.limbThickness])"><TresMesh :position="v(s.model.frontPaw.forearmPosition)" :rotation="r([0,0,side*.06])"><TresCylinderGeometry :args="s.model.frontPaw.forearm"/><TresMeshStandardMaterial :color="appearance.palette.coat" :roughness=".26"/></TresMesh><TresMesh :position="v(s.model.frontPaw.tipPosition)" :scale="sc(s.model.frontPaw.tipScale,appearance.proportions.pawScale)"><TresSphereGeometry :args="[s.model.frontPaw.tipRadius,24,24]"/><TresMeshStandardMaterial :color="appearance.palette.coatWarm" :roughness=".26"/></TresMesh></TresGroup>
<TresGroup v-for="side in [-1,1]" :key="`hp${side}`" :position="v([side*s.model.hindPaw.offset[0],s.model.hindPaw.offset[1],s.model.hindPaw.offset[2]])"><TresMesh :rotation="r([s.model.hindPaw.legRotation[0],0,side*s.model.hindPaw.legRotation[2]])"><TresCylinderGeometry :args="s.model.hindPaw.leg"/><TresMeshStandardMaterial :color="appearance.palette.coatShadow" :roughness=".32"/></TresMesh><TresMesh :position="v(s.model.hindPaw.tipPosition)" :scale="sc(s.model.hindPaw.tipScale,appearance.proportions.pawScale)"><TresSphereGeometry :args="[s.model.hindPaw.tipRadius,24,24]"/><TresMeshStandardMaterial :color="appearance.palette.coatWarm" :roughness=".3"/></TresMesh></TresGroup>
<TresMesh :position="v(s.model.chestCore.position)"><TresSphereGeometry :args="[s.model.chestCore.radius,32,32]"/><TresMeshStandardMaterial :color="appearance.palette.secondaryGlow" :emissive="appearance.palette.secondaryGlow" :emissive-intensity="s.model.chestCore.emissiveIntensity" :metalness=".25" :roughness=".12"/></TresMesh><TresGroup v-if="appearance.symbols.chest.enabled&&chestTexture" :position="v([0,-.26,.765])" :scale="v([.34*appearance.symbols.chest.scale,.34*appearance.symbols.chest.scale,.34])"><TresPointLight :color="appearance.symbols.chest.color" :intensity="appearance.symbols.chest.glowIntensity*.55"/><TresMesh><TresPlaneGeometry/><TresMeshBasicMaterial :map="chestTexture" transparent :side="DoubleSide"/></TresMesh></TresGroup><TresGroup v-if="appearance.symbols.back.enabled&&backTexture" :position="v([0,-.2,-.84])" :rotation="r([0,Math.PI,0])" :scale="v([.48*appearance.symbols.back.scale,.48*appearance.symbols.back.scale,.48])"><TresMesh><TresPlaneGeometry/><TresMeshBasicMaterial :map="backTexture" transparent :side="DoubleSide"/></TresMesh></TresGroup></template>
