<!--
  文件职责 / File responsibility
  使用扩展经典方案渲染云狐头部、耳朵、眼睛、口鼻和触角。
  Renders the Cloud Fox head, ears, eyes, muzzle, and antennae from the extension classic scheme.
-->
<script setup lang="ts">
import { useLoop } from '@tresjs/core'
import { Color, Euler, Vector3 } from 'three'
import type { Group, MeshStandardMaterial } from 'three'
import { EXTENSION_CLASSIC_CLOUD_FOX_SCHEME } from '~/domain/chrome-extension-cloud-fox-profile'
import type { CloudFoxStudioBehavior } from '~/domain/pet-studio-phase4'
import type { MultiSpeciesAppearanceRecipe } from '~/domain/pet-species-registry'
const props=defineProps<{appearance:MultiSpeciesAppearanceRecipe;behavior:CloudFoxStudioBehavior}>(),s=EXTENSION_CLASSIC_CLOUD_FOX_SCHEME
const v=(a:readonly number[])=>new Vector3(a[0]||0,a[1]||0,a[2]||0),sc=(a:readonly number[],n=1)=>new Vector3((a[0]||0)*n,(a[1]||0)*n,(a[2]||0)*n),r=(a:readonly number[])=>new Euler(a[0]||0,a[1]||0,a[2]||0),head=shallowRef<Group>(),left=shallowRef<Group>(),right=shallowRef<Group>(),materials=shallowRef<MeshStandardMaterial[]>([])
const headScale=computed(()=>sc(s.model.head.scale,props.appearance.proportions.headScale)),eyeX=computed(()=>s.model.head.eyeOffset[0]*props.appearance.proportions.eyeSpacing),earX=computed(()=>s.model.head.earOffset[0]*props.appearance.proportions.earScale),antennaX=computed(()=>props.appearance.antennaDesign.spacing/2),antennaY=computed(()=>props.appearance.proportions.antennaScale*(props.appearance.antennaDesign.length/s.model.antenna.rod[2])),antennaRod=computed(()=>[s.model.antenna.rod[0]*(props.appearance.antennaDesign.thickness/s.model.antenna.rod[1]),props.appearance.antennaDesign.thickness,s.model.antenna.rod[2],s.model.antenna.rod[3]] as const),cheekOpacity=computed(()=>['greeting','jumping'].includes(props.behavior)?.32:0)
function refGlow(x:unknown){const m=x as MeshStandardMaterial|null;if(m&&!materials.value.includes(m))materials.value.push(m)}const rainbow=new Color()
useLoop().onBeforeRender(({elapsed,delta})=>{if(head.value)head.value.rotation.z+=((props.behavior==='greeting'?Math.sin(elapsed*5.8)*.13:props.behavior==='resting'?.08:0)-head.value.rotation.z)*Math.min(1,delta*7);const a=Math.sin(elapsed*props.appearance.glow.pulseSpeed*3.2)*.05;if(left.value)left.value.rotation.z=-props.appearance.antennaDesign.tilt+a;if(right.value)right.value.rotation.z=props.appearance.antennaDesign.tilt-a;const p=1+Math.sin(elapsed*props.appearance.glow.pulseSpeed*3.5)*.12;if(props.appearance.glow.mode==='rainbow')rainbow.setHSL((elapsed*.11)%1,.86,.64);for(const m of materials.value){m.emissiveIntensity=props.appearance.glow.intensity*p;if(props.appearance.glow.mode==='rainbow'){m.color.copy(rainbow);m.emissive.copy(rainbow)}}})
</script>
<template><TresGroup ref="head" :position="v(s.model.head.position)" :scale="headScale"><TresGroup v-for="side in [-1,1]" :key="`ear${side}`" :position="v([side*earX,s.model.head.earOffset[1],s.model.head.earOffset[2]])" :rotation="r([0,0,side*s.model.head.earRotationZ])" :scale="v([appearance.proportions.earScale,appearance.proportions.earScale,appearance.proportions.earScale])"><TresMesh><TresSphereGeometry v-if="['rounded','floppy'].includes(appearance.parts.ears)" :args="[.34,28,28]"/><TresBoxGeometry v-else-if="appearance.parts.ears==='mechanical'" :args="[.54,.86,.42]"/><TresConeGeometry v-else :args="s.model.head.earOuter"/><TresMeshStandardMaterial :color="appearance.parts.ears==='mechanical'?appearance.palette.coatShadow:appearance.palette.coat" :roughness=".3"/></TresMesh><TresMesh v-if="appearance.parts.ears==='pointed'" :position="v(s.model.head.earInnerPosition)" :scale="v(s.model.head.earInnerScale)"><TresConeGeometry :args="s.model.head.earInner"/><TresMeshStandardMaterial :color="appearance.palette.primaryGlow" :emissive="appearance.palette.primaryGlow" :emissive-intensity=".25"/></TresMesh></TresGroup>
<template v-if="appearance.parts.antenna!=='none'"><TresGroup v-for="side in [-1,1]" :key="`a${side}`" :ref="side<0?(n:any)=>left=n:(n:any)=>right=n" :position="v([side*antennaX,s.model.antenna.offset[1],s.model.antenna.offset[2]])" :rotation="r([s.model.antenna.rotation[0],side<0?s.model.antenna.rotation[1]:-s.model.antenna.rotation[1],side*appearance.antennaDesign.tilt])" :scale="v([appearance.proportions.antennaScale,antennaY,appearance.proportions.antennaScale])"><TresMesh :position="v(s.model.antenna.rodPosition)"><TresCylinderGeometry :args="antennaRod"/><TresMeshStandardMaterial :color="appearance.palette.coatWarm" :roughness=".22" :metalness=".04"/></TresMesh><TresMesh :position="v([side*s.model.antenna.tipPosition[0],s.model.antenna.tipPosition[1],s.model.antenna.tipPosition[2]])"><TresTorusGeometry v-if="appearance.parts.antennaTip==='ring'" :args="[.12,.035,12,28]"/><TresDodecahedronGeometry v-else-if="appearance.parts.antennaTip==='crystal'" :args="[.11,0]"/><TresSphereGeometry v-else :args="[s.model.antenna.tipRadius,20,20]"/><TresMeshStandardMaterial :ref="refGlow" :color="appearance.palette.antennaGlow" :emissive="appearance.palette.antennaGlow" :emissive-intensity="1.6" transparent :opacity=".9" :roughness=".1"/></TresMesh><TresMesh :position="v([side*s.model.antenna.tipPosition[0],s.model.antenna.tipPosition[1],s.model.antenna.tipPosition[2]])" :scale="v([s.model.antenna.auraScale,s.model.antenna.auraScale,s.model.antenna.auraScale])"><TresSphereGeometry :args="[s.model.antenna.tipRadius,16,16]"/><TresMeshBasicMaterial :color="appearance.palette.primaryGlow" transparent :opacity=".14" :depth-write="false"/></TresMesh></TresGroup></template>
<TresMesh><TresSphereGeometry :args="[s.model.head.radius,64,64]"/><TresMeshStandardMaterial :color="appearance.palette.coat" :roughness=".28" :metalness=".04"/></TresMesh><TresMesh :position="v(s.model.head.muzzlePosition)" :scale="v(s.model.head.muzzleScale)"><TresSphereGeometry :args="[s.model.head.muzzleRadius,48,48]"/><TresMeshStandardMaterial :color="s.palette.muzzle" :roughness=".34"/></TresMesh>
<template v-if="appearance.parts.eyes!=='visor'"><TresGroup v-for="side in [-1,1]" :key="`e${side}`" :position="v([side*eyeX,s.model.head.eyeOffset[1],s.model.head.eyeOffset[2]])"><TresMesh :scale="appearance.parts.eyes==='sleepy'?v([.19,.07,.08]):appearance.parts.eyes==='oval'?v([.13,.25,.1]):sc(s.model.head.eyeScale,appearance.proportions.eyeScale)"><TresDodecahedronGeometry v-if="['spark','diamond'].includes(appearance.parts.eyes)"/><TresSphereGeometry v-else :args="[1,32,32]"/><TresMeshStandardMaterial :color="appearance.palette.eye" :roughness=".08"/></TresMesh><TresMesh v-if="appearance.parts.eyes==='round'" :position="v(s.model.head.eyeHighlightPosition)" :scale="v(s.model.head.eyeHighlightScale)"><TresSphereGeometry/><TresMeshBasicMaterial :color="appearance.palette.secondaryGlow"/></TresMesh></TresGroup></template><TresMesh v-else :position="v([0,s.model.head.eyeOffset[1],s.model.head.eyeOffset[2]])" :scale="v([.72,.16,.08])"><TresBoxGeometry/><TresMeshStandardMaterial :color="appearance.palette.eye" :emissive="appearance.palette.secondaryGlow" :emissive-intensity=".42"/></TresMesh>
<TresMesh v-for="side in [-1,1]" :key="`c${side}`" :position="v([side*s.model.head.cheekOffset[0],s.model.head.cheekOffset[1],s.model.head.cheekOffset[2]])" :scale="v(s.model.head.cheekScale)"><TresSphereGeometry/><TresMeshBasicMaterial :color="s.palette.cheek" transparent :opacity="cheekOpacity"/></TresMesh><TresMesh :position="v(s.model.head.nosePosition)" :scale="v(s.model.head.noseScale)"><TresSphereGeometry/><TresMeshStandardMaterial :color="s.palette.nose" :roughness=".22"/></TresMesh><TresGroup :position="v(s.model.head.mouthPosition)"><TresMesh :scale="v(s.model.head.mouthScale)"><TresSphereGeometry/><TresMeshStandardMaterial :color="s.palette.mouth" :roughness=".2"/></TresMesh><TresMesh :position="v(s.model.head.tonguePosition)" :scale="v(s.model.head.tongueScale)"><TresSphereGeometry/><TresMeshBasicMaterial :color="s.palette.tongue"/></TresMesh></TresGroup></TresGroup></template>
