<script setup lang="ts">
import { useLoop } from '@tresjs/core'
import { CatmullRomCurve3, Euler, Vector3 } from 'three'
import type { Group } from 'three'
import { resolveSpeciesBehavior, type MultiSpeciesAppearanceRecipe } from '~/domain/pet-species-registry'
import type { CloudFoxStudioBehavior, CloudFoxStudioView } from '~/domain/pet-studio-phase4'
const props=defineProps<{appearance:MultiSpeciesAppearanceRecipe;behavior:CloudFoxStudioBehavior;view:CloudFoxStudioView}>()
const v3=(x:number,y:number,z:number)=>new Vector3(x,y,z),rot=(x:number,y:number,z:number)=>new Euler(x,y,z)
const presentation=shallowRef<Group>(),motion=shallowRef<Group>(),head=shallowRef<Group>(),tail=shallowRef<Group>()
const activeBehavior=computed(()=>resolveSpeciesBehavior('moon-cat',props.behavior))
const viewY=computed(()=>({front:0,left:Math.PI/2,back:Math.PI,right:-Math.PI/2}[props.view]))
const tailCurve=computed(()=>new CatmullRomCurve3([v3(0,0,0),v3(-.45,.12,0),v3(-.82,.55,0),v3(-.5,.98*props.appearance.speciesParts.moonTailCurl,0),v3(-.08,.78,0)]))
useLoop().onBeforeRender(({elapsed,delta})=>{if(!presentation.value||!motion.value||!head.value)return;presentation.value.rotation.y+=(viewY.value-presentation.value.rotation.y)*Math.min(1,delta*7);const greeting=activeBehavior.value==='greeting',jumping=activeBehavior.value==='jumping',stretching=activeBehavior.value==='stretching',resting=activeBehavior.value==='resting';motion.value.position.y+=((jumping?Math.max(0,Math.sin(elapsed*4))*.55:resting?-.2:.08)+Math.sin(elapsed*1.8)*.025-motion.value.position.y)*Math.min(1,delta*6);motion.value.scale.y+=((stretching?1.12:resting?.82:1)-motion.value.scale.y)*Math.min(1,delta*5);head.value.rotation.z+=((greeting?Math.sin(elapsed*5)*.14:resting?.1:0)-head.value.rotation.z)*Math.min(1,delta*7);if(tail.value)tail.value.rotation.z=Math.sin(elapsed*(greeting?5:2))*(greeting?.16:.05)})
</script>
<template>
<TresGroup ref="presentation"><TresGroup ref="motion" :position="v3(0,.08,0)">
<TresGroup ref="tail" :position="v3(-.72,-.48,-.25)" :rotation="rot(.1,.35,-.1)"><TresMesh><TresTubeGeometry :args="[tailCurve,36,.16,14,false]"/><TresMeshStandardMaterial :color="appearance.palette.coatShadow" :emissive="appearance.palette.tailGlow" :emissive-intensity="appearance.glow.tailEnabled?appearance.glow.intensity*.5:0"/></TresMesh></TresGroup>
<TresMesh :position="v3(0,-.32,0)" :scale="v3(.92*appearance.proportions.bodyWidth,1.02*appearance.proportions.bodyHeight,.78*appearance.proportions.bodyDepth)" cast-shadow><TresSphereGeometry :args="[1,56,56]"/><TresMeshStandardMaterial :color="appearance.palette.shade"/></TresMesh>
<TresGroup v-for="side in [-1,1]" :key="`paw-${side}`" :position="v3(side*.34,-1.02,.5)"><TresMesh :scale="v3(.16,.28,.16)"><TresSphereGeometry :args="[1,22,22]"/><TresMeshStandardMaterial :color="appearance.palette.coat"/></TresMesh><TresMesh :position="v3(0,-.19,.05)" :scale="v3(.22,.13,.24)"><TresSphereGeometry :args="[1,22,22]"/><TresMeshStandardMaterial :color="appearance.palette.highlight"/></TresMesh></TresGroup>
<TresGroup ref="head" :position="v3(0,.82,.08)" :scale="v3(appearance.proportions.headScale,appearance.proportions.headScale,appearance.proportions.headScale)"><TresMesh :scale="v3(1,.86,.9)"><TresSphereGeometry :args="[.88,56,56]"/><TresMeshStandardMaterial :color="appearance.palette.coat"/></TresMesh>
<TresGroup v-for="side in [-1,1]" :key="`ear-${side}`" :position="v3(side*.56,.62,-.03)" :rotation="rot(0,0,side*.12)"><TresMesh :scale="appearance.parts.ears==='mechanical'?v3(.8,1,.55):v3(1,1,.7)"><TresBoxGeometry v-if="appearance.parts.ears==='mechanical'" :args="[.5,.72,.38]"/><TresConeGeometry v-else :args="[.34,.82,4]"/><TresMeshStandardMaterial :color="appearance.parts.ears==='mechanical'?appearance.palette.shade:appearance.palette.coat" :metalness="appearance.parts.ears==='mechanical'?.7:0"/></TresMesh></TresGroup>
<TresMesh v-for="side in [-1,1]" :key="`eye-${side}`" :position="v3(side*.29,.06,.78)" :scale="appearance.parts.eyes==='sleepy'?v3(.18,.065,.07):v3(.15,.21,.09)"><TresDodecahedronGeometry v-if="['spark','diamond'].includes(appearance.parts.eyes)" :args="[1,0]"/><TresSphereGeometry v-else :args="[1,26,26]"/><TresMeshStandardMaterial :color="appearance.palette.eye" :emissive="['spark','diamond'].includes(appearance.parts.eyes)?appearance.palette.secondaryGlow:'#000000'" :emissive-intensity=".55"/></TresMesh>
<TresMesh :position="v3(0,-.23,.98)" :scale="v3(.1,.08,.06)"><TresSphereGeometry :args="[1,20,20]"/><TresMeshStandardMaterial color="#27253a"/></TresMesh>
<TresGroup v-if="appearance.speciesParts.whiskers.enabled" :position="v3(0,-.22,.93)"><template v-for="side in [-1,1]" :key="`whisker-side-${side}`"><TresMesh v-for="row in [-1,0,1]" :key="`${side}-${row}`" :position="v3(side*(.25+appearance.speciesParts.whiskers.length/2),row*appearance.speciesParts.whiskers.spread*.25,0)" :rotation="rot(0,0,row*.1)"><TresCylinderGeometry :args="[.008,.008,appearance.speciesParts.whiskers.length,8]"/><TresMeshBasicMaterial :color="appearance.speciesParts.whiskers.color"/></TresMesh></template></TresGroup>
<TresGroup v-if="appearance.speciesParts.foreheadMark.enabled" :position="v3(0,.34,.82)"><TresMesh :scale="v3(.12,.12,.035)"><TresTorusGeometry v-if="appearance.speciesParts.foreheadMark.style==='crescent'" :args="[.65,.22,12,28,Math.PI*1.45]"/><TresDodecahedronGeometry v-else :args="[1,appearance.speciesParts.foreheadMark.style==='star'?1:0]"/><TresMeshStandardMaterial :color="appearance.speciesParts.foreheadMark.color" :emissive="appearance.speciesParts.foreheadMark.color" :emissive-intensity="appearance.speciesParts.foreheadMark.glowIntensity"/></TresMesh></TresGroup>
</TresGroup></TresGroup></TresGroup>
</template>
