<!--
  文件职责 / File responsibility
  提供高级动作层、镜像预设、IK、洋葱皮、运动轨迹、中断策略和本地音效轨道控制。
  Provides advanced motion layers, mirroring/presets, IK, onion skinning, motion paths, interruption policy, and local audio-track controls.
-->
<script setup lang="ts">
import type { MotionAudioCue, MotionInterruptionMode, MotionLayerMode, MotionPosePresetId } from '@yk-pets/pet-core'
import { useStudioMotionEditorStore } from '~/stores/studio-motion-editor'
import StudioMotionCurveEditor from './StudioMotionCurveEditor.vue'
const editor = useStudioMotionEditorStore()
const layerName=ref('Layer'); const layerMode=ref<MotionLayerMode>('override')
const ikSide=ref<'left'|'right'>('left'); const ikX=ref(.7); const ikY=ref(.25)
const audioInput=ref<HTMLInputElement|null>(null); const audioStatus=ref(''); let previousTime=0
const presets: readonly [MotionPosePresetId,string][]=[['neutral','中性'],['wave-left','左手挥动'],['wave-right','右手挥动'],['squat','下蹲'],['look-up','抬头']]
watch(()=>editor.playheadTimeMs,current=>{if(!editor.playing||!editor.draft){previousTime=current;return}const cues=editor.draft.audioCues.filter(cue=>editor.playbackDirection===-1?(cue.timeMs<previousTime&&cue.timeMs>=current):(current>=previousTime?(cue.timeMs>previousTime&&cue.timeMs<=current):(cue.timeMs>previousTime||cue.timeMs<=current)));for(const cue of cues)playCue(cue);previousTime=current})
function playCue(cue: MotionAudioCue){if(!import.meta.client)return;if(cue.kind==='local-audio'&&cue.dataUrl){const audio=new Audio(cue.dataUrl);audio.volume=cue.volume;void audio.play().catch(()=>{});return}const Context=window.AudioContext||((window as Window & {webkitAudioContext?:typeof AudioContext}).webkitAudioContext);if(!Context)return;const context=new Context();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.value=cue.frequency;gain.gain.value=cue.volume;oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+cue.durationMs/1000);oscillator.addEventListener('ended',()=>void context.close())}

function updateLayerMode(layerId:string,event:Event){editor.updateLayer(layerId,{mode:(event.target as HTMLSelectElement).value as MotionLayerMode})}
function updateLayerWeight(layerId:string,event:Event){editor.updateLayer(layerId,{weight:Number((event.target as HTMLInputElement).value)})}
function updateLayerEnabled(layerId:string,event:Event){editor.updateLayer(layerId,{enabled:(event.target as HTMLInputElement).checked})}
function updateInterruptionMode(event:Event){editor.updateInterruptionPolicy({mode:(event.target as HTMLSelectElement).value as MotionInterruptionMode})}
function updateBlendOut(event:Event){editor.updateInterruptionPolicy({blendOutMs:Number((event.target as HTMLInputElement).value)})}
function addTone(){editor.addAudioCue({name:'Tone',kind:'tone',frequency:440,durationMs:180,volume:.35})}
async function importAudio(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;if(file.size>500_000){audioStatus.value='音频超过 500 KB 本地预算';return}const dataUrl=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)});editor.addAudioCue({name:file.name,kind:'local-audio',frequency:440,durationMs:1000,volume:.5,dataUrl});audioStatus.value=`已添加 ${file.name}`;(event.target as HTMLInputElement).value=''}
</script>
<template>
  <section v-if="editor.draft" class="advanced-tools">
    <header><small>ADVANCED MOTION</small><h3>高级动画工具</h3></header>
    <StudioMotionCurveEditor :asset="editor.draft" :channel-id="editor.selectedChannelId" :layer-id="editor.activeLayerId" :selected-keyframe-ids="editor.selectedKeyframeIds" @interpolation="editor.setSelectedInterpolation" @tangents="editor.setSelectedTangents" />
    <section class="tool-card"><h4>可视辅助</h4><div class="toggles"><label><input v-model="editor.onionSkin" type="checkbox"> 洋葱皮</label><label><input v-model="editor.showMotionPath" type="checkbox"> 根节点运动轨迹</label></div></section>
    <section class="tool-card"><h4>镜像与预设</h4><button @click="editor.mirrorDraft">左右镜像全部轨道</button><div class="preset-grid"><button v-for="[id,label] in presets" :key="id" @click="editor.applyPreset(id)">{{ label }}</button></div></section>
    <section class="tool-card"><h4>动作层</h4><div class="layer-create"><input v-model="layerName"><select v-model="layerMode"><option value="override">Override</option><option value="additive">Additive</option></select><button @click="editor.addLayer(layerName,layerMode)">添加层</button></div><div class="layers"><div v-for="layer in editor.draft.layers" :key="layer.id" :class="{active:layer.id===editor.activeLayerId}"><button @click="editor.activeLayerId=layer.id">{{ layer.name }}</button><select :value="layer.mode" @change="updateLayerMode(layer.id,$event)"><option value="override">override</option><option value="additive">additive</option></select><input :value="layer.weight" type="number" min="0" max="1" step=".05" @change="updateLayerWeight(layer.id,$event)"><label><input :checked="layer.enabled" type="checkbox" @change="updateLayerEnabled(layer.id,$event)">on</label><button v-if="layer.id!=='base'" @click="editor.deleteLayer(layer.id)">×</button></div></div><button @click="editor.assignSelectedChannelToLayer(editor.activeLayerId)">把当前通道分配到活动层</button></section>
    <section class="tool-card"><h4>中断策略</h4><div class="two"><select :value="editor.draft.interruptionPolicy.mode" @change="updateInterruptionMode"><option value="immediate">立即</option><option value="finish-loop">完成循环</option><option value="blend-out">淡出</option></select><input :value="editor.draft.interruptionPolicy.blendOutMs" type="number" min="0" max="5000" @change="updateBlendOut"></div></section>
    <section class="tool-card"><h4>前爪 IK 辅助</h4><div class="ik"><select v-model="ikSide"><option value="left">左前爪</option><option value="right">右前爪</option></select><input v-model.number="ikX" type="number" step=".05" aria-label="IK X"><input v-model.number="ikY" type="number" step=".05" aria-label="IK Y"><button @click="editor.applyFrontPawIk(ikSide,ikX,ikY)">写入 IK 姿态</button></div></section>
    <section class="tool-card"><h4>本地音效轨道</h4><div class="audio-actions"><button @click="addTone">在指针添加音调</button><button @click="audioInput?.click()">导入本地音频</button><input ref="audioInput" hidden type="file" accept="audio/*" @change="importAudio"></div><div class="cues"><button v-for="cue in editor.draft.audioCues" :key="cue.id" @click="editor.removeAudioCue(cue.id)"><b>{{ cue.timeMs }}</b><span>{{ cue.name }}</span><small>{{ cue.kind }} · 点击删除</small></button></div><small>{{ audioStatus }} · 仅保存在本地动作数据，不上传。</small></section>
  </section>
</template>
<style scoped>.advanced-tools{display:grid;gap:8px}.advanced-tools>header small{color:#78829f;font:800 8px/1 ui-monospace,monospace;letter-spacing:.13em}.advanced-tools h3,.advanced-tools h4{margin:3px 0 0}.advanced-tools h3{font-size:13px}.advanced-tools h4{font-size:10px}.tool-card{display:grid;gap:7px;padding:9px;border:1px solid #ffffff12;border-radius:10px;background:#ffffff04}.advanced-tools button,.advanced-tools input,.advanced-tools select{min-height:30px;padding:0 6px;border:1px solid #ffffff1d;border-radius:7px;color:#fff;background:#090e1b}.toggles,.two,.audio-actions{display:grid;grid-template-columns:1fr 1fr;gap:5px}.toggles label{display:flex;align-items:center;gap:5px;color:#b8c0da;font-size:8px}.toggles input{min-height:auto}.preset-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:4px}.layer-create{display:grid;grid-template-columns:1fr 90px auto;gap:4px}.layers{display:grid;gap:4px}.layers>div{display:grid;grid-template-columns:1fr 82px 52px 42px 26px;gap:3px}.layers>div.active{outline:1px solid #52e0d055;border-radius:7px}.layers label{display:flex;align-items:center;gap:2px;color:#adb6cf;font-size:8px}.layers label input{min-height:auto}.ik{display:grid;grid-template-columns:80px 1fr 1fr auto;gap:4px}.cues{display:grid;gap:3px}.cues button{display:grid;grid-template-columns:44px 1fr auto;text-align:left;align-items:center}.cues small,.tool-card>small{color:#747f9e;font-size:7px}</style>
