<script setup lang="ts">
import { PET_STUDIO_PRESETS, type AppearanceApplyScope, type PetStyleId } from '~/domain/pet-studio-phase4'
import { usePetAppearanceStore } from '~/stores/pet-appearance'
const store = usePetAppearanceStore()
const schemeName = ref('')
const scopes: Array<[AppearanceApplyScope,string]> = [['all','全部应用'],['shape','只应用造型'],['proportions','只应用比例'],['colors','只应用颜色'],['glow','只应用发光']]
const styles: Array<[PetStyleId,string,string]> = [['cute','可爱','圆润比例与软萌五官'],['mechanical','机械','硬表面、目镜与霓虹能量'],['nebula','星云','深色毛色和彩虹能量'],['crystal','水晶','通透浅色与高强度光晕']]
const locks: Array<[keyof typeof store.locks,string]> = [['shape','造型'],['proportions','比例'],['colors','颜色'],['glow','发光'],['tail','尾巴'],['antenna','触角'],['symbols','标志']]
onMounted(() => store.hydrate())
function saveScheme(){ store.saveCustomScheme(schemeName.value || `自定义方案 ${store.customSchemes.length+1}`); schemeName.value='' }
</script>
<template>
<main class="page"><header><div><NuxtLink to="/studio">← 返回宠物工坊</NuxtLink><small>PRESETS & STYLES</small><h1>预设与风格</h1><p>选择应用范围、锁定参数，再安全地探索新造型。</p></div><NuxtLink class="primary" to="/studio">查看实时模型</NuxtLink></header>
<section class="settings"><label>应用范围<select v-model="store.applyScope"><option v-for="[id,label] in scopes" :key="id" :value="id">{{label}}</option></select></label><fieldset><legend>随机生成锁定</legend><label v-for="[key,label] in locks" :key="key"><input v-model="store.locks[key]" type="checkbox">{{label}}</label></fieldset><button @click="store.randomize">按锁定参数随机生成</button></section>
<h2>内置预设</h2><section class="grid"><article v-for="preset in PET_STUDIO_PRESETS" :key="preset.id"><span>{{preset.style}}</span><h3>{{preset.label}}</h3><p>{{preset.labelEn}}</p><button @click="store.applyBuiltInPreset(preset.id)">应用</button></article></section>
<h2>风格规则</h2><section class="grid"><article v-for="[id,label,description] in styles" :key="id"><span>STYLE</span><h3>{{label}}</h3><p>{{description}}</p><button @click="store.applyStyle(id)">应用规则</button></article></section>
<h2>我的方案</h2><section class="custom"><div><input v-model="schemeName" maxlength="32" placeholder="方案名称"><button @click="saveScheme">保存当前方案</button></div><article v-for="scheme in store.customSchemes" :key="scheme.id"><strong>{{scheme.name}}</strong><small>{{new Date(scheme.createdAt).toLocaleString()}}</small><div><button @click="store.applyCustomScheme(scheme.id)">应用</button><button @click="store.deleteCustomScheme(scheme.id)">删除</button></div></article><p v-if="!store.customSchemes.length">尚未保存自定义方案。</p></section>
</main>
</template>
<style scoped>
:global(body){margin:0;background:#080a12}:global(*){box-sizing:border-box}.page{min-height:100vh;padding:34px;color:#f4f6ff;background:radial-gradient(circle at 80% 0,#7066ff33,transparent 28%),#080a12;font-family:Inter,system-ui}.page>header{display:flex;justify-content:space-between;align-items:end;gap:24px;max-width:1280px;margin:auto auto 28px}.page a{color:#8fe9dd}.page small{display:block;margin-top:14px;color:#8d86ff}.page h1{margin:6px 0;font-size:52px}.page header p{margin:0;color:#aeb7d8}.primary,button{display:inline-flex;border:1px solid #7066ffaa;border-radius:10px;padding:10px 14px;color:#fff;background:#7066ff33;text-decoration:none;cursor:pointer}.settings,.custom,.grid{max-width:1280px;margin:auto}.settings{display:flex;align-items:center;flex-wrap:wrap;gap:14px;padding:16px;border:1px solid #ffffff1a;border-radius:16px;background:#ffffff08}.settings label{display:flex;gap:8px;align-items:center}.settings select,.custom input{min-height:40px;border:1px solid #ffffff22;border-radius:9px;padding:8px;color:#fff;background:#111526}.settings fieldset{display:flex;flex-wrap:wrap;gap:9px;border:1px solid #ffffff18;border-radius:12px}.page>h2{max-width:1280px;margin:30px auto 12px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.grid article,.custom article{padding:16px;border:1px solid #ffffff18;border-radius:14px;background:#ffffff08}.grid span{color:#8fe9dd;font-size:11px}.grid h3{margin:8px 0 3px}.grid p{margin:0 0 14px;color:#aeb7d8}.custom>div,.custom article{display:flex;align-items:center;justify-content:space-between;gap:10px}.custom{display:flex;flex-direction:column;gap:10px}.custom article small{color:#8f99bd}.custom article div{display:flex;gap:8px}@media(max-width:850px){.grid{grid-template-columns:1fr}.page>header{align-items:start;flex-direction:column}.custom>div,.custom article{align-items:flex-start;flex-direction:column}}
</style>
